### ISSUE TITLE
setup-server-hp/setup_server_hp.sh need be updated

### ISSUE THREAD

**Issue by billwang-au** [y-ken/setup-server-hp#1]
In setup-server-hp/setup_server_hp.

---
# setup repository

wget https://raw.github.com/y-ken/setup-server-hp/master/yum.repos.d/hp.repo -P /etc/yum.repos.d/
yum -y install hpacucli hp-health

---

The url (https://raw.github.com/y-ken/setup-server-hp/master/yum.repos.d/hp.repo) content is too old, should be updated

from: 
baseurl=http://downloads.linux.hp.com/SDR/downloads/ProLiantSupportPack/RedHat/$releasever/$basearch/current/

to:

baseurl=http://downloads.linux.hp.com/SDR/downloads/servicepackforproliant/RedHat/$releasever/$basearch/current/

**Comment by y-ken** [comment]
Thank you for reporting issue!!
I have updated these urls in this commit https://github.com/y-ken/setup-server-hp/commit/d084809df446e55bbcacfea859cccdb06ecadf53

**Comment by y-ken** [comment]
Hi @bw57899 
if you like this repository, please click start button for this.
https://github.com/y-ken/setup-server-hp/stargazers

**Comment by y-ken** [comment]
Thank you!
